### ISSUE TITLE
Test Coverage Badge from GH Action

### ISSUE THREAD

**Issue by KKegel** [modicio/modicio#25]

**Comment by AlexNDRmac** [comment]
Hi @KKegel, I can help with it, but coverage badge will require to add external service for code coverage aggregation, like a Codecov. So, if you don't mind - you will need to create an account in Codecov, allow this app to read your repository.
Also you need to setup Codecov token for your repository. After these steps - you'll be able to see code coverage of your project with Codecov and have a badge with coverage percentage in Readme :)
If you agree with this approach - I would like to help you with CI steps.

**Comment by KKegel** [comment]
I don't actually want to use an external service. If it does not work out of the box (I must admit that it did not check the requirements beforehand) then maybe we just can not do it...
