### ISSUE TITLE
AssociationRule not found in ModelModificationSpec

### ISSUE THREAD

**Issue by Rumo99** [modicio/modicio#53]
In the integration test for model modifications the test for removing an AssociationRule fails unexpectedly because the rule is not retrieved by unfolding the Type. However, if a new Type is generated from the TypeFactory immediately beforehand - without adding it to the Type! -, the test succeeds. Tests for ParentRelationRule and AttributeRule work, as does the test for adding an AssociationRule.

**Comment by KKegel** [comment]
Can you check if the Rule is present during writing it to the registry? It must be either are bug in deconstructing or constructing the the type

**Comment by Rumo99** [comment]
@KKegel It must be, because the case of adding an AssociationRule succeeds, and all Rules are found, including the one apparently missing. In branch 47-a, just (un-)commenting the creation of the new type in the problematic test case changes the result. With the new type it is successfully retrieved from the registry.

**Comment by KKegel** [comment]
@Rumo99 whats the status of this? can we close the issue?
